FROM golang:latest as builder

WORKDIR /go/src/codeface
RUN go get -u github.com/go-bindata/go-bindata/...
COPY . .
RUN make install

FROM heroku/heroku:20
MAINTAINER Owen Ou

RUN useradd -m -s /usr/bin/bash dyno
USER dyno
WORKDIR /home/dyno

COPY --from=builder /go/bin/cf /usr/local/bin/cf
COPY --from=builder /go/src/codeface/template/ /home/dyno/template/

ENTRYPOINT ["cf"]
CMD ["worker", "--template", "/home/dyno/template"]
